sh_binary(
    name = "build_pip_pkg",
    srcs = ["build_pip_pkg.sh"],
    data = [
        "LICENSE",
        "MANIFEST.in",
        "setup.py",
        "//tensorflow_backprojection:backprojection_py",
        "//tensorflow_stolt_interp:stolt_interp_py",
    ],
)
